### ISSUE TITLE
read sm / encoder count from within function

### ISSUE THREAD

**Issue by robvoi** [jamon/pi-pico-pio-quadrature-encoder#1]
Your code works great! Using it in my small robot project. But I have a question. 

I am trying to move the part for reading the encoder count from main code to a callback function fora hardware timer.
When I do this, the pi doesn't even seem to completely boot. 

Do you have an idea on why this may happen or how to move this portion of the code to a function?

`pio_sm_exec_wait_blocking(pio, sm, pio_encode_in(pio_x, 32));
 uint x = pio_sm_get_blocking(pio, sm);`

**Comment by jamon** [comment]
This was actually my first micropython--so I don't really know my way around it that well, but one thing to check is to make sure that you aren't calling that code before the pio has been initialized.

Additionally, I'm not sure what a hardware timer solution entails in micropython, but if that equates to an interrupt, you don't want to do blocking code in there--you should set a variable in there to tell it to do the read, then read in your main loop, or you'd need to use non-blocking methods--but you'll want to make sure the IN, X 32 occurs before the pio_sm_get.  

The other option you have is to modify the PIO program so that it pushes to the input FIFO either automatically (meaning you'd have to always be reading it to keep it clear/updated) or check the output fifo regularly to see if the CPU wants an update, and if so, push to the input fifo.  Then you'd just push to the output fifo then read from the input one from the CPU in order to get a value.

**Comment by robvoi** [comment]
Yes, with hardware timer I mean a timer interrupt. 

I am using c, so your c example.

What I am trying to do is to read the encoder exactly every 100ms. But without reading it every main loop. That’s why I try to use the timer interrupt. 

I’ll try to wrap my head around your suggestions. Thanks a lot.

**Comment by jamon** [comment]
Oh, I'm really out of it, yeah that's the C.  In that case I think it gets easier.  I'd throw a variable in "shouldReadEncoder" and set that from the interrupt, but do the work in the main loop, only if that is set.

**Comment by robvoi** [comment]
Good approach.Thanks a lot.
