### ISSUE TITLE
Max counts per second

### ISSUE THREAD

**Issue by PiWizard3852** [jamon/pi-pico-pio-quadrature-encoder#9]
I am planning on using this library with 8 encoders, each of which I expect to reach at most 150000 counts per second. Can this library/the pico itself adequately handle this number of counts each second without skipping?

**Comment by ardlc-1212** [comment]
Hi, every signal change takes roughly 5 clock cycles of the pio, assuming you run it at 125mhz (full speed for pico without overclocking) it would take 16 (10+6 for schmitt triggers) cycles per line on encoders (the system can only count at 1/2 the resolution above 4 encoders due to not having enough state machines. For 16 cycles 7.8mhz should be possible **excluding the read requests each of which take 1 clock cycle for the state machines** so a safe option would be 5 million cps which is for each encoder separately, so you are far below the limits.
